import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import cx from 'classnames';
import { useState, Dispatch, SetStateAction } from 'react';
import { Scroll } from '../../utils/Scroll';

interface Props {
  language: any;
  setLanguage: Dispatch<SetStateAction<any>>;
}

const langugaes = [
  'Not applicable',
  'Abkhazian',
  'Afar',
  'Afrikaans',
  'Akan',
  'Akkadian',
  'Albanian',
  'American Sign Langugage',
  'Amharic',
  'Arabic',
  'Aramaic',
  'Armenian',
  'Assamese',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Bangla',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bhojpuri',
  'Bislama',
  'Bodo',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Cantonese',
  'Cantonese (Hong Kong)',
  'Catalan',
  'Cherokee',
  'Chinese',
  'Chinese (China)',
  'Chinese (Hong Kong)',
  'Chinese (Simplified)',
  'Chinese (Singapore)',
  'Chinese (Taiwan)',
  'Chinese (Traditional)',
  'Choctaw',
  'Coptic',
  'Corsican',
  'Cree',
  'Croatian',
  'Czech',
  'Danish',
  'Dogri',
  'Dutch',
  'Dutch (Belgium)',
  'Dutch (Netherlands)',
  'Dzongkha',
  'English',
  'English (Canada)',
  'English (India)',
  'English (Ireland)',
  'English (United Kingdom)',
  'English (United States)',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'French (Belgium)',
  'French (Canada)',
  'French (France)',
  'French (Switzerland)',
  'Fula',
  'Galician',
  'Ganda',
  'Georgian',
  'German',
  'German (Austria)',
  'German (Germany)',
  'German (Switzerland)',
  'Greek',
  'Guarani',
  'Gujarati',
  'Gusii',
  'Haitian Creole',
  'Hakka Chinese',
  'Hakka Chinese (Taiwan)',
  'Haryanvi',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hindi (Latin)',
  'Hiri Motu',
  'Hungarian',
  'Icelandic',
  'Igbo',
  'Indonesian',
  'Interlingua',
  'Interlingue',
  'Inuktitut',
  'Inupiaq',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kalaallisut',
  'Kalenjin',
  'Kamba',
  'Kannada',
  'Kashmiri',
  'Kazakh',
  'Khmer',
  'Kikuyu',
  'Kinyarwanda',
  'Klingon',
  'Konkani',
  'Korean',
  'Kurdish',
  'Kyrgyz',
  'Ladino',
  'Lao',
  'Latin',
  'Latvian',
  'Lingala',
  'Lithuanian',
  'Luba-Katanga',
  'Luo',
  'Luxembourgish',
  'Luyia',
  'Macedonian',
  'Maithili',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Manipuri',
  'Māori',
  'Marathi',
  'Masai',
  'Meru',
  'Min Nan Chinese',
  'Min Nan Chinese (Taiwan)',
  'Mixe',
  'Mizo',
  'Mongolian',
  'Mongolian (Mongolian)',
  'Nauru',
  'Navajo',
  'Nepali',
  'Nigerian Pidgin',
  'North Ndebele',
  'Northern Sotho',
  'Norwegian',
  'Occitan',
  'Odia',
  'Oromo',
  'Papiamento',
  'Pashto',
  'Persian',
  'Persian (Afghanistan)',
  'Persian (Iran)',
  'Polish',
  'Portuguese',
  'Portuguese (Brazil)',
  'Portuguese (Portugal)',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Romanian (Moldova)',
  'Romansh',
  'Rundi',
  'Russian',
  'Russian (Latin)',
  'Samoan',
  'Sango',
  'Sanskrit',
  'Santali',
  'Sardinian',
  'Scottish Gaelic',
  'Serbian',
  'Serbian (Cyrillic)',
  'Serbian (Latin)',
  'Serbo-Croatian',
  'Sherdukpen',
  'Shona',
  'Sicilian',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'South Ndebele',
  'Southern Sotho',
  'Spanish',
  'Spanish (Latin America)',
  'Spanish (Mexico)',
  'Spanish (Spain)',
  'Spanish (United States)',
  'Sundanese',
  'Swahili',
  'Swati',
  'Swedish',
  'Tagalog',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tok Pisin',
  'Tongan',
  'Tsonga',
  'Tswana',
  'Turkish',
  'Turkmen',
  'Twi',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Volapük',
  'Võro',
  'Welsh',
  'Western Frisian',
  'Wolaytta',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu',
];

export function VideoLangugageDropdown({
  language,
  setLanguage,
}: Props) {
  return (
    <DropdownMenuPrimitive.Portal>
      <DropdownMenuPrimitive.Content
        align="start"
        sideOffset={5}
        className={cx(
          'flex flex-col h-[300px] space-y-0.5 radix-side-top:animate-slide-up radix-side-bottom:animate-slide-down',
          'rounded-lg py-1 shadow-md w-[470px]',
          'bg-white dark:bg-gray-800'
        )}
      >
        <Scroll>
          <>
            {langugaes.map((value: any, index: number) => {
              return (
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    setLanguage(value);
                  }}
                  className="w-full focus:ring-0 focus:border-none hover:ring-0"
                  key={index}
                >
                  <DropdownMenuPrimitive.Item className="hover:bg-gray-100 py-1.5 rounded w-full focus:ring-0 focus:border-none">
                    <span className="px-2.5 text-sm silka-regular text-gray-600">
                      {value}
                    </span>
                  </DropdownMenuPrimitive.Item>
                </button>
              );
            })}
          </>
        </Scroll>
      </DropdownMenuPrimitive.Content>
    </DropdownMenuPrimitive.Portal>
  );
}
